# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x64)
  x_glfw_config = debug_x64
  x_glew_config = debug_x64
  x_glm_config = debug_x64
  main_config = debug_x64
  common_config = debug_x64
endif
ifeq ($(config),release_x64)
  x_glfw_config = release_x64
  x_glew_config = release_x64
  x_glm_config = release_x64
  main_config = release_x64
  common_config = release_x64
endif

PROJECTS := x-glfw x-glew x-glm main common

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

x-glfw:
ifneq (,$(x_glfw_config))
	@echo "==== Building x-glfw ($(x_glfw_config)) ===="
	@${MAKE} --no-print-directory -C external -f x-glfw.make config=$(x_glfw_config)
endif

x-glew:
ifneq (,$(x_glew_config))
	@echo "==== Building x-glew ($(x_glew_config)) ===="
	@${MAKE} --no-print-directory -C external -f x-glew.make config=$(x_glew_config)
endif

x-glm:
ifneq (,$(x_glm_config))
	@echo "==== Building x-glm ($(x_glm_config)) ===="
	@${MAKE} --no-print-directory -C external -f x-glm.make config=$(x_glm_config)
endif

main: common x-glfw x-glew x-glm
ifneq (,$(main_config))
	@echo "==== Building main ($(main_config)) ===="
	@${MAKE} --no-print-directory -C src -f Makefile config=$(main_config)
endif

common:
ifneq (,$(common_config))
	@echo "==== Building common ($(common_config)) ===="
	@${MAKE} --no-print-directory -C common -f Makefile config=$(common_config)
endif

clean:
	@${MAKE} --no-print-directory -C external -f x-glfw.make clean
	@${MAKE} --no-print-directory -C external -f x-glew.make clean
	@${MAKE} --no-print-directory -C external -f x-glm.make clean
	@${MAKE} --no-print-directory -C src -f Makefile clean
	@${MAKE} --no-print-directory -C common -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x64"
	@echo "  release_x64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   x-glfw"
	@echo "   x-glew"
	@echo "   x-glm"
	@echo "   main"
	@echo "   common"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"